### ISSUE TITLE
System properties / environment variables for default config

### ISSUE THREAD

**Issue by timja** [jenkinsci/azure-keyvault-plugin#38]
https://github.com/jenkinsci/azure-keyvault-plugin/pull/33 adds a credential provider.

In order for this to be useful to JCasC, configuration will need to be supplied to this plugin before JCasC is invoked so that JCasC can resolve credentials directly from the keyvault.

Two credential types need to be supported + the vault url:

Microsoft Azure Service principal:
```
client id
client secret
subscription id
tenant id
```

Managed identity for Azure resources

Both environment variables and system properties should be used to give flexibility.

suggested configuration:
```
-Djenkins.azure-keyvault.uami.enabled=true
-Djenkins.azure-keyvault.vault=https://<your-vault-name>.vault.azure.net

AZURE_KEYVAULT_UAMI_ENABLED=...
AZURE_KEYVAULT_VAULT=...

```

```
-Djenkins.azure-keyvault.sp.client_id=...
-Djenkins.azure-keyvault.sp.client_secret=...
-Djenkins.azure-keyvault.sp.subscription_id=...
-Djenkins.azure-keyvault.sp.tenant_id=...
-Djenkins.azure-keyvault.vault=https://<your-vault-name>.vault.azure.net

AZURE_KEYVAULT_SP_CLIENT_ID=...
AZURE_KEYVAULT_SP_CLIENT_SECRET=...
AZURE_KEYVAULT_SP_SUBSCRIPTION_ID=...
AZURE_KEYVAULT_SP_TENANT_ID=...

AZURE_KEYVAULT_VAULT=...

```

These should be saved as credentials and the default configuration updated.
A special ID should be used for this: default-azure-credentials, possibly allow overriding it.

If the default configuration is already set then these should overwrite it.
Ideally system property wins, but behaviour can be undefined as you shouldn't set both.
If both SP and UAMI are set then an error should be thrown
A log message at info should be emitted to say that this config has been written.

**Comment by timja** [comment]
cc @gavinfish if you have any thoughts

**Comment by gavinfish** [comment]
I  will take this one.

**Comment by gavinfish** [comment]
I am a little confused about this issue. There should be no changes for JCasC whether adding credential provider. Something like below should work.

```
credentials:
  system:
    domainCredentials:
    - credentials:
      - azureImds:
          azureEnvName: "Azure"
          id: "imds"
          scope: GLOBAL
unclassified:
  azureKeyVault:
    credentialID: "imds"
    keyVaultURL: "https://***-vault.vault.azure.net/"
```
